import tempfile
import unittest
from pathlib import Path

from data_intelligence_sdk.core.types import (
    CapabilityRequirement,
    DataCorpusPackage,
    ExecutionSpec,
)
import data_intelligence_sdk.engines.report as report_module
from data_intelligence_sdk.engines.report import ReportEngine
from data_intelligence_sdk.methods.csv import register_csv_methods
from data_intelligence_sdk.runtime.engine_runtime import EngineRuntimeContext
from data_intelligence_sdk.runtime.method_hub import MethodHub


class FakeInvokeResponse:
    def __init__(self, content):
        self.content = content


class FakePromptModel:
    def __init__(self, content="# Model Report\n\nGenerated by LangChain."):
        self.content = content
        self.prompts = []

    def invoke(self, prompt):
        self.prompts.append(prompt)
        return FakeInvokeResponse(self.content)


class ReportEngineTests(unittest.TestCase):
    def test_router_prefers_trusted_methods_for_postgres_and_vectordb(self) -> None:
        router = report_module.RouterAgent(FakePromptModel("not json"))
        methods = [
            {"tool_name": "inspect_postgres_table"},
            {"tool_name": "inspect_postgres_tables"},
            {"tool_name": "count_postgres_tables"},
            {"tool_name": "aggregate_postgres_table"},
            {"tool_name": "inspect_vector_chunks"},
            {"tool_name": "get_vector_stats"},
        ]
        sources = [
            "postgresql://demo/db?schema=vectordb",
            "postgresql://demo/db",
        ]

        table_route = router.run(
            {
                "description": "Inspect orders",
                "required_data": {"tables": ["orders"], "columns": ["revenue"]},
                "operation": {"kind": "inspect"},
            },
            methods,
            sources,
        )
        vector_route = router.run(
            {
                "description": "Inspect document chunks",
                "required_data": {"vector_collections": ["document_chunks"]},
                "operation": {"kind": "inspect"},
            },
            methods,
            sources,
        )

        self.assertEqual(table_route["tool_name"], "inspect_postgres_table")
        self.assertEqual(table_route["arguments"]["table"], "orders")
        self.assertEqual(vector_route["tool_name"], "inspect_vector_chunks")

        count_route = router.run(
            {
                "description": "Fetch row counts for all core tables",
                "required_data": {"tables": ["customers", "orders"]},
                "operation": {"kind": "inspect"},
            },
            methods,
            sources,
        )
        stats_route = router.run(
            {
                "description": "Fetch vector stats including chunk count",
                "required_data": {"vector_collections": ["document_chunks"]},
                "operation": {"kind": "inspect"},
            },
            methods,
            sources,
        )

        self.assertEqual(count_route["tool_name"], "count_postgres_tables")
        self.assertEqual(stats_route["tool_name"], "get_vector_stats")

    def test_plan_agent_infers_known_data_for_underspecified_steps(self) -> None:
        model = FakePromptModel(
            '{"steps":['
            '{"step_id":"load-core-tables","description":"Load all core tables",'
            '"required_data":{},"operation":{"kind":"load"}},'
            '{"step_id":"load-vectors","description":"Load document chunks from vectordb",'
            '"required_data":{},"operation":{"kind":"load"}},'
            '{"step_id":"compute-metrics","description":"Compute order count and revenue",'
            '"required_data":{},"operation":{"kind":"aggregate",'
            '"parameters":{"metrics":[]}}},'
            '{"step_id":"assemble-final","description":"Assemble final report",'
            '"required_data":{},"operation":{"kind":"assemble"}}]}'
        )
        corpus = DataCorpusPackage(
            sources=[
                "postgresql://demo/db?schema=vectordb",
                "postgresql://demo/db",
            ],
            schemas={
                "tables": {
                    "customers": {"columns": ["customer_id", "segment"]},
                    "orders": {"columns": ["order_id", "revenue"]},
                },
                "vector_collections": {"document_chunks": {}},
            },
        )

        plan = report_module.PlanAgent(model).run(
            ExecutionSpec(intent="report", objective="Summarize the corpus"),
            corpus,
        )
        steps = {step["step_id"]: step for step in plan["steps"]}

        self.assertEqual(
            steps["load-core-tables"]["required_data"]["tables"],
            ["customers", "orders"],
        )
        self.assertEqual(
            steps["load-vectors"]["required_data"]["vector_collections"],
            ["document_chunks"],
        )
        self.assertEqual(
            steps["compute-metrics"]["required_data"]["tables"],
            ["orders"],
        )
        self.assertNotIn("assemble-final", steps)
    def test_vectordb_only_data_requirements_create_vector_only_scope(self) -> None:
        vector_source = "postgresql://demo/db?schema=vectordb"
        corpus = DataCorpusPackage(
            sources=[vector_source, "postgresql://demo/db"],
            schemas={
                "tables": {"orders": {"columns": ["order_id"]}},
                "vector_collections": {
                    "document_chunks": {"columns": ["chunk_id", "content"]}
                },
            },
        )

        scope = report_module._scope_from_spec(
            ExecutionSpec(
                intent="report",
                objective="Summarize the vectordb",
                data_requirements=[vector_source],
            ),
            corpus,
        )

        self.assertEqual(scope["sources"], [vector_source])
        self.assertEqual(scope["tables"], [])
        self.assertEqual(scope["vector_collections"], ["document_chunks"])
        self.assertTrue(scope["explicit"])

    def test_plan_agent_normalizes_non_object_inputs_and_outputs(self) -> None:
        model = FakePromptModel(
            '{"steps":[{"step_id":"inspect-chunks","required_data":'
            '{"tables":[],"vector_collections":["document_chunks"]},'
            '"inputs":["document_chunks"],"outputs":["summary"],'
            '"operation":"inspect","fallback":"omit"}]}'
        )
        corpus = DataCorpusPackage(
            sources=["postgresql://demo/db?schema=vectordb"],
            schemas={
                "vector_collections": {
                    "document_chunks": {"columns": ["chunk_id", "content"]}
                }
            },
        )

        plan = report_module.PlanAgent(model).run(
            ExecutionSpec(intent="report", objective="Summarize document chunks"),
            corpus,
        )

        step = plan["steps"][0]
        self.assertEqual(step["inputs"], [])
        self.assertIsInstance(step["outputs"][0], dict)
        self.assertEqual(step["operation"], {"kind": "analyze"})
        self.assertEqual(step["fallback"]["action"], "complete_no_data")

    def test_plan_agent_omits_report_rendering_steps_from_data_dag(self) -> None:
        model = FakePromptModel(
            '{"steps":['
            '{"step_id":"inspect-chunks","required_data":'
            '{"tables":[],"vector_collections":["document_chunks"]},'
            '"operation":{"kind":"inspect"}},'
            '{"step_id":"generate-report","required_data":{},'
            '"operation":{"kind":"generate_report"}}]}'
        )
        corpus = DataCorpusPackage(
            sources=["postgresql://demo/db?schema=vectordb"],
            schemas={"vector_collections": {"document_chunks": {}}},
        )

        plan = report_module.PlanAgent(model).run(
            ExecutionSpec(intent="report", objective="Summarize document chunks"),
            corpus,
        )

        self.assertEqual(
            [step["step_id"] for step in plan["steps"]],
            ["inspect-chunks"],
        )

    def test_report_agent_falls_back_for_malformed_structured_sections(self) -> None:
        model = FakePromptModel(
            '{"title":"Corpus report","summary":"Summary",'
            '"sections":["invalid section"]}'
        )
        agent = report_module.ReportAgent(model)
        spec = ExecutionSpec(intent="report", objective="Summarize the corpus")
        template_instance = {
            "template_id": "executive-overview",
            "template_version": "1.0.0",
            "instance_id": "template-instance",
            "revision": 1,
            "sections": [],
        }

        report = agent.run_structured(
            spec,
            template_instance,
            [],
            [],
            {"sources": [], "scope": {}},
        )
        rendered = report_module.ReportRenderer().render(report)

        self.assertEqual(report["title"], spec.objective)
        self.assertEqual(rendered[0]["format"], "markdown")

    def test_report_engine_runs_full_fallback_agent_workflow_from_metadata(
        self,
    ) -> None:
        corpus = DataCorpusPackage(
            sources=[
                "postgresql://demo:demo@localhost:5432/data_corpus?schema=vectordb",
                "postgresql://demo:demo@localhost:5432/data_corpus",
            ],
            schemas={
                "tables": {
                    "orders": {"columns": ["order_id", "revenue"]},
                    "customers": {"columns": ["customer_id", "segment"]},
                },
                "vector_collections": {
                    "document_chunks": {"columns": ["chunk_id", "content"]}
                },
            },
            metadata={
                "catalog": {
                    "summary": "Mock package for report tests.",
                    "datasets": [
                        {
                            "name": "orders",
                            "kind": "db_table",
                            "description": "Order revenue records.",
                        },
                        {
                            "name": "document_chunks",
                            "kind": "vectordb_collection",
                            "description": "Document chunk records.",
                        },
                    ],
                }
            },
        )

        output = ReportEngine().run(
            ExecutionSpec(intent="report", objective="Create a report"),
            corpus,
            EngineRuntimeContext(),
        )

        self.assertEqual(output.engine_name, "report")
        self.assertIn("# Data Intelligence Report", output.result)
        self.assertIn("Mock package", output.result)
        self.assertIn("## Key Metrics", output.result)
        self.assertIn("orders", output.result)
        self.assertIn("document_chunks", output.result)
        self.assertEqual(output.metadata["report_format"], "markdown")
        self.assertEqual(output.metadata["generation_mode"], "fallback")
        self.assertEqual(output.metadata["workflow"][0], "Plan Agent")
        step_names = [step.name for step in output.trace.steps]
        self.assertIn("plan_agent", step_names)
        self.assertIn("router_agent", step_names)
        self.assertIn("code_agent", step_names)
        self.assertIn("validator_agent", step_names)
        self.assertIn("datascience_agent", step_names)
        self.assertIn("report_agent", step_names)
        self.assertEqual(step_names[-1], "renderer")

    def test_report_engine_routes_existing_method_to_datascience_agent(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            csv_path = Path(temp_dir) / "sales.csv"
            csv_path.write_text(
                "country,revenue\nUS,10\nCA,7\n",
                encoding="utf-8",
            )
            method_hub = MethodHub()
            register_csv_methods(method_hub)
            runtime = EngineRuntimeContext(method_hub=method_hub)

            output = ReportEngine().run(
                ExecutionSpec(intent="report", objective="Create a sales report"),
                DataCorpusPackage(sources=[str(csv_path)]),
                runtime,
            )

        self.assertIn("# Data Intelligence Report", output.result)
        self.assertEqual(output.trace.method_calls[0].method_name, "scan_csv")
        self.assertEqual(output.trace.method_calls[0].status, "completed")
        self.assertIn("record_count", output.metadata["all_steps_data"][0]["aggregated_data"])

    def test_report_engine_uses_english_langchain_prompts_for_all_agents(
        self,
    ) -> None:
        model = FakePromptModel()

        output = ReportEngine(llm=model, max_generation_attempts=1).run(
            ExecutionSpec(intent="report", objective="Summarize revenue"),
            DataCorpusPackage(metadata={"catalog": {"summary": "Revenue corpus."}}),
            EngineRuntimeContext(),
        )

        self.assertEqual(output.result, "# Model Report\n\nGenerated by LangChain.")
        prompt_text = "\n".join(str(prompt) for prompt in model.prompts)
        self.assertIn("You are the Data Planning Agent", prompt_text)
        self.assertIn("You are the Routing Agent", prompt_text)
        self.assertIn("You are the Data Programming Agent", prompt_text)
        self.assertIn("You are the Validation Agent", prompt_text)
        self.assertIn("You are the Data Science Agent", prompt_text)
        self.assertIn("You are the Report Agent", prompt_text)
        self.assertNotIn("Tác tử", prompt_text)

    def test_prompt_constants_are_english(self) -> None:
        prompt_names = [
            "PLAN_AGENT_PROMPT",
            "TEMPLATE_AGENT_PROMPT",
            "ROUTER_AGENT_PROMPT",
            "CODE_AGENT_PROMPT",
            "VALIDATOR_AGENT_PROMPT",
            "DATASCIENCE_AGENT_PROMPT",
            "CHART_AGENT_PROMPT",
            "REPORT_AGENT_PROMPT",
            "STRUCTURED_REPORT_AGENT_PROMPT",
        ]

        for prompt_name in prompt_names:
            prompt = getattr(report_module, prompt_name)
            self.assertIn("You are", prompt)
            self.assertNotIn("Bạn là", prompt)
            self.assertNotIn("Tác tử", prompt)

    def test_confirmed_orders_spec_produces_scoped_structured_plan(self) -> None:
        source = "postgresql://data_intelligence:data_intelligence@localhost:2345/data_corpus"
        selected_columns = [
            "order_id",
            "customer_id",
            "country",
            "status",
            "revenue",
        ]
        method_hub = MethodHub()
        method_hub.register(
            "inspect_orders",
            lambda: [
                {
                    "country": "US",
                    "status": "completed",
                    "order_count": 2,
                    "total_revenue": 30.0,
                },
                {
                    "country": "CA",
                    "status": "pending",
                    "order_count": 1,
                    "total_revenue": 7.0,
                },
            ],
            capability_names=["inspect_data", "aggregate_data"],
            metadata={"description": "Inspect and aggregate the orders table."},
        )
        spec = ExecutionSpec(
            intent="report",
            objective=(
                "Create a structured report describing the orders table in the "
                "available data package without using document chunks or document sources."
            ),
            data_requirements=[source],
            capability_requirements=[
                CapabilityRequirement(name="inspect_data"),
                CapabilityRequirement(name="aggregate_data"),
                CapabilityRequirement(name="generate_report"),
            ],
            constraints={
                "scope": {
                    "sources": [source],
                    "tables": ["orders"],
                    "vector_collections": [],
                    "documents": [],
                },
                "columns": {"orders": selected_columns},
                "filters": {},
                "group_by": ["country", "status"],
                "metrics": [
                    {
                        "name": "order_count",
                        "field": "order_id",
                        "aggregation": "count",
                    },
                    {
                        "name": "total_revenue",
                        "field": "revenue",
                        "aggregation": "sum",
                    },
                ],
                "output_format": "structured_report",
                "language": None,
                "evidence_required": True,
                "selected_data_context": {
                    "selected_sources": [source],
                    "selected_tables": ["orders"],
                    "selected_columns": {"orders": selected_columns},
                    "selected_vector_collections": [],
                    "selected_documents": [],
                    "missing_information": [],
                    "confidence": 0.99,
                },
            },
            confirmed=True,
            engine_hint="report",
        )
        corpus = DataCorpusPackage(
            sources=[source, "postgresql://example/document_store"],
            schemas={
                "tables": {
                    "orders": {"columns": selected_columns},
                    "customers": {"columns": ["customer_id", "segment"]},
                },
                "vector_collections": {
                    "document_chunks": {"columns": ["chunk_id", "content"]}
                },
            },
            metadata={
                "catalog": {
                    "summary": "Orders plus document data.",
                    "datasets": [
                        {"name": "orders", "kind": "db_table"},
                        {"name": "document_chunks", "kind": "vectordb_collection"},
                    ],
                }
            },
        )

        output = ReportEngine().run(
            spec,
            corpus,
            EngineRuntimeContext(method_hub=method_hub),
        )

        self.assertIsInstance(output.result, dict)
        self.assertEqual(output.metadata["orchestration"], "langgraph")
        self.assertEqual(output.metadata["report_format"], "structured_report")
        self.assertEqual(output.metadata["plan"]["scope"]["tables"], ["orders"])
        self.assertEqual(output.metadata["plan"]["scope"]["vector_collections"], [])
        self.assertEqual(output.metadata["plan"]["scope"]["documents"], [])
        self.assertEqual(
            [step["step_id"] for step in output.metadata["plan"]["steps"]],
            ["inspect-orders", "aggregate-orders"],
        )
        aggregate_step = output.metadata["plan"]["steps"][1]
        self.assertEqual(
            aggregate_step["operation"]["parameters"]["group_by"],
            ["country", "status"],
        )
        self.assertEqual(
            [metric["name"] for metric in aggregate_step["operation"]["parameters"]["metrics"]],
            ["order_count", "total_revenue"],
        )
        self.assertEqual(
            output.metadata["template_instance"]["template_id"],
            "segment-comparison",
        )
        serialized_plan = report_module._json_dumps(output.metadata["plan"])
        self.assertNotIn("document_chunks", serialized_plan)
        self.assertNotIn("customers", serialized_plan)
        trace_names = [step.name for step in output.trace.steps]
        self.assertIn("template_agent", trace_names)
        self.assertIn("dag_scheduler", trace_names)
        self.assertIn("chart_input_assembler", trace_names)
        self.assertEqual(trace_names[-1], "renderer")


if __name__ == "__main__":
    unittest.main()
