import tempfile
import unittest
from pathlib import Path

from data_intelligence_sdk.core.types import DataCorpusPackage, ExecutionSpec
import data_intelligence_sdk.engines.report as report_module
from data_intelligence_sdk.engines.report import ReportEngine
from data_intelligence_sdk.methods.csv import register_csv_methods
from data_intelligence_sdk.runtime.engine_runtime import EngineRuntimeContext
from data_intelligence_sdk.runtime.method_hub import MethodHub


class FakeInvokeResponse:
    def __init__(self, content):
        self.content = content


class FakePromptModel:
    def __init__(self, content="# Model Report\n\nGenerated by LangChain."):
        self.content = content
        self.prompts = []

    def invoke(self, prompt):
        self.prompts.append(prompt)
        return FakeInvokeResponse(self.content)


class ReportEngineTests(unittest.TestCase):
    def test_report_engine_runs_full_fallback_agent_workflow_from_metadata(
        self,
    ) -> None:
        corpus = DataCorpusPackage(
            sources=[
                "postgresql://demo:demo@localhost:5432/data_corpus?schema=vectordb",
                "postgresql://demo:demo@localhost:5432/data_corpus",
            ],
            schemas={
                "tables": {
                    "orders": {"columns": ["order_id", "revenue"]},
                    "customers": {"columns": ["customer_id", "segment"]},
                },
                "vector_collections": {
                    "document_chunks": {"columns": ["chunk_id", "content"]}
                },
            },
            metadata={
                "catalog": {
                    "summary": "Mock package for report tests.",
                    "datasets": [
                        {
                            "name": "orders",
                            "kind": "db_table",
                            "description": "Order revenue records.",
                        },
                        {
                            "name": "document_chunks",
                            "kind": "vectordb_collection",
                            "description": "Document chunk records.",
                        },
                    ],
                }
            },
        )

        output = ReportEngine().run(
            ExecutionSpec(intent="report", objective="Create a report"),
            corpus,
            EngineRuntimeContext(),
        )

        self.assertEqual(output.engine_name, "report")
        self.assertIn("# Data Intelligence Report", output.result)
        self.assertIn("Mock package", output.result)
        self.assertIn("## Key Metrics", output.result)
        self.assertIn("orders", output.result)
        self.assertIn("document_chunks", output.result)
        self.assertEqual(output.metadata["report_format"], "markdown")
        self.assertEqual(output.metadata["generation_mode"], "fallback")
        self.assertEqual(output.metadata["workflow"][0], "Plan Agent")
        step_names = [step.name for step in output.trace.steps]
        self.assertIn("plan_agent", step_names)
        self.assertIn("router_agent", step_names)
        self.assertIn("code_agent", step_names)
        self.assertIn("validator_agent", step_names)
        self.assertIn("datascience_agent", step_names)
        self.assertEqual(step_names[-1], "report_agent")

    def test_report_engine_routes_existing_method_to_datascience_agent(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            csv_path = Path(temp_dir) / "sales.csv"
            csv_path.write_text(
                "country,revenue\nUS,10\nCA,7\n",
                encoding="utf-8",
            )
            method_hub = MethodHub()
            register_csv_methods(method_hub)
            runtime = EngineRuntimeContext(method_hub=method_hub)

            output = ReportEngine().run(
                ExecutionSpec(intent="report", objective="Create a sales report"),
                DataCorpusPackage(sources=[str(csv_path)]),
                runtime,
            )

        self.assertIn("# Data Intelligence Report", output.result)
        self.assertEqual(output.trace.method_calls[0].method_name, "scan_csv")
        self.assertEqual(output.trace.method_calls[0].status, "completed")
        self.assertIn("record_count", output.metadata["all_steps_data"][0]["aggregated_data"])

    def test_report_engine_uses_english_langchain_prompts_for_all_agents(
        self,
    ) -> None:
        model = FakePromptModel()

        output = ReportEngine(llm=model, max_generation_attempts=1).run(
            ExecutionSpec(intent="report", objective="Summarize revenue"),
            DataCorpusPackage(metadata={"catalog": {"summary": "Revenue corpus."}}),
            EngineRuntimeContext(),
        )

        self.assertEqual(output.result, "# Model Report\n\nGenerated by LangChain.")
        prompt_text = "\n".join(str(prompt) for prompt in model.prompts)
        self.assertIn("You are the Data Planning Agent", prompt_text)
        self.assertIn("You are the Routing Agent", prompt_text)
        self.assertIn("You are the Data Programming Agent", prompt_text)
        self.assertIn("You are the Validation Agent", prompt_text)
        self.assertIn("You are the Data Science Agent", prompt_text)
        self.assertIn("You are the Report Agent", prompt_text)
        self.assertNotIn("Tác tử", prompt_text)

    def test_prompt_constants_are_english(self) -> None:
        prompt_names = [
            "PLAN_AGENT_PROMPT",
            "ROUTER_AGENT_PROMPT",
            "CODE_AGENT_PROMPT",
            "VALIDATOR_AGENT_PROMPT",
            "DATASCIENCE_AGENT_PROMPT",
            "REPORT_AGENT_PROMPT",
        ]

        for prompt_name in prompt_names:
            prompt = getattr(report_module, prompt_name)
            self.assertIn("You are", prompt)
            self.assertNotIn("Bạn là", prompt)
            self.assertNotIn("Tác tử", prompt)


if __name__ == "__main__":
    unittest.main()
