[system]
language = "en"
api_keys = []
encrypt_key = "your_secret_key"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 8000

[service.web.database]
type = "sqlite"
path = "pilot/meta_data/disdk.db"

[rag.storage]
[rag.storage.vector]
type = ""
persist_path = ""

# Model Configurations
[models]
[[models.llms]]
name = "${env:LLM_MODEL_NAME}"
provider = "proxy/openrouter"
api_base = "https://openrouter.ai/api/v1"
api_key = "${env:OPENROUTER_API_KEY}"

[[models.embeddings]]
name = "${env:EMBEDDING_MODEL_NAME}"
provider = "proxy/openrouter"
api_url = "${https://openrouter.ai/api/v1/embeddings}"
api_key = "${env:OPENROUTER_API_KEY}"